### ISSUE TITLE
Connect Backend to Frontend

### ISSUE THREAD

**Issue by CodyRichter** [CodyRichter/ElenaApp#12]
Login, navigation endpoint, etc...

**Comment by sohanshow** [comment]
Connecting backend and front-end done. Implemented Google cloud API which takes words as input from the user and sends lat and long values to backend to get the routing data.

**Comment by sohanshow** [comment]
Feature of location suggestion is showing errors for the time being. 98 percent done. Works without it too.

**Comment by sohanshow** [comment]
The entire front-end works now (we also got place suggestion as the user types now) but there is something weird that happens. When I boot up the page and type the location, Even though there are values in startLocation and endLocation, they come up to be "undefined" on the console. But when I click on the maximize elevation or minimize elevation, it works miraculously. Need a little bit of checking on that. Problematic file is Navigation.tsx

**Comment by sohanshow** [comment]
Done
